name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Build Hat_V1
      run: pio run -e Hat_V1
    - name: Build Hat_V2
      run: pio run -e Hat_V2
    - name: Build Hat_V2_AP
      run: pio run -e Hat_V2_AP
    - name: Build Hat_V2_BLE
      run: pio run -e Hat_V2_BLE
    - name: Build Glasses_Wifi
      run: pio run -e Glasses_Wifi
    - name: Build Glasses_AP
      run: pio run -e Glasses_AP
    - name: Build Glasses_AP_BLE
      run: pio run -e Glasses_AP_BLE
    - name: Build Glasses_BLE
      run: pio run -e Glasses_BLE
    - name: Deploy
      env:
        SUPER_SECRET: ${{ secrets.TOKEN }} 
      run: |
        mv .pio/build/Hat_V1/firmware.bin    octoWifi_Hat_V1.bin
        mv .pio/build/Hat_V2/firmware.bin    octoWifi_Hat_V2.bin
        mv .pio/build/Hat_V2_AP/firmware.bin octoWifi_Hat_V2_AP.bin
        mv .pio/build/Hat_V2_BLE/firmware.bin octoWifi_Hat_V2_BLE.bin

        mv .pio/build/Glasses_Wifi/firmware.bin   octoWifi_Glasses_Wifi.bin
        mv .pio/build/Glasses_AP/firmware.bin     octoWifi_Glasses_AP.bin
        mv .pio/build/Glasses_AP_BLE/firmware.bin octoWifi_Glasses_AP_BLE.bin
        mv .pio/build/Glasses_BLE/firmware.bin    octoWifi_Glasses_BLE.bin

        curl -sSF file=@octoWifi_Hat_V1.bin     'http://antoine.doussaud.org:25478/upload?token='$SUPER_SECRET
        curl -sSF file=@octoWifi_Hat_V2.bin     'http://antoine.doussaud.org:25478/upload?token='$SUPER_SECRET
        curl -sSF file=@octoWifi_Hat_V2_AP.bin  'http://antoine.doussaud.org:25478/upload?token='$SUPER_SECRET
        curl -sSF file=@octoWifi_Hat_V2_BLE.bin 'http://antoine.doussaud.org:25478/upload?token='$SUPER_SECRET

        curl -sSF file=@octoWifi_Glasses_Wifi.bin   'http://antoine.doussaud.org:25478/upload?token='$SUPER_SECRET
        curl -sSF file=@octoWifi_Glasses_AP.bin     'http://antoine.doussaud.org:25478/upload?token='$SUPER_SECRET
        curl -sSF file=@octoWifi_Glasses_AP_BLE.bin 'http://antoine.doussaud.org:25478/upload?token='$SUPER_SECRET
        curl -sSF file=@octoWifi_Glasses_BLE.bin    'http://antoine.doussaud.org:25478/upload?token='$SUPER_SECRET
        
        echo `TZ="Europe/Paris" date '+%F %T'`" git:"`git rev-parse --short HEAD` > octoWifi.info
        curl -sSF file=@octoWifi.info 'http://antoine.doussaud.org:25478/upload?token='$SUPER_SECRET


